#+BEGIN_HTML
---
layout: post
title: "Emacs: a faithful companion when configuring your system"
date: 2013-06-19 20:31
comments: true
categories: emacs
---
#+END_HTML


Emacs is awesome as we all know and one of the reasons it is awesome
is tramp. This little extension-plugin-package-whatever is bundled
with emacs and lets you access files remotely as if they were in your
filesystem. It can also open files with sudo from the same
non-priviledged emacs instance. How it works is you prepend ‘/sudo::’
to the filename and you are good to go! And this is all really cool.

Being the greedy bastard that I am however, this was not enough for
me. I don’t want to have to find the file again and prepend sudo, this
will also open a new buffer so I will have to deal with having two
buffers of the same file and this can be quite annoying after a while.

Thankfully emacs is awesome as we have established and it was
extremely easy with a couple of lines of elisp to have it login as
root before writing to disk if I try to save without permissions. Here
is my code:

#+NAME: Give sudo to current file editing session
#+BEGIN_SRC scm
(defadvice save-buffer (around save-buffer-as-root-around activate)
  "Use sudo to save the current buffer."
  (interactive "p")
  (if (and (buffer-file-name)
           (file-accessible-directory-p (current-directory))
           (not (file-writable-p (buffer-file-name))))
      (let ((buffer-file-name (format "/sudo::%s" buffer-file-name)))
	ad-do-it)
    ad-do-it))
#+END_SRC
